// <auto-generated />
namespace E_Commerce.Core.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "202312302030492_updateAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
